tests:
  - name: nuevos
    n_inliers: 950
    n_outliers: 50
    datasets:
      - moons
      - circles
      - blobs
    models:
      LOF:
        n_neighbors: 3
        algorithm: auto
        contamination: 0.05
      CBLOF:
        # n_clusters: 3
        contamination: 0.05
      HBOS:
        # n_bins: auto
        contamination: 0.05
  - name: test1
    n_inliers: 950
    n_outliers: 50
    datasets: 
      - moons
      - circles
      - blobs
    models:
      IForest:
        n_estimators: 300
        max_samples: 64
        contamination: 0.05
        random_state: 42
      KNN:
        n_neighbors: 3
        method: largest
        contamination: 0.05
      OCSVM:
        kernel: rbf
        nu: 0.05
        gamma: 0.1
        contamination: 0.05
      ECOD:
        contamination: 0.05
  - name: test2
    n_inliers: 5000
    n_outliers: 1000
    datasets:
      - moons
      - circles
      - blobs
    models:
      IForest:
        n_estimators: 300
        max_samples: 64
        contamination: 0.05
        random_state: 42
      KNN:
        n_neighbors: 3
        method: largest
        contamination: 0.05
      OCSVM:
        kernel: rbf
        nu: 0.05
        gamma: 0.1
        contamination: 0.05
      ECOD:
        contamination: 0.05
  - name: test3
    n_inliers: 5
    n_outliers: 10
    datasets:
      - moons
      - circles
      - blobs
    models:
      IForest:
        n_estimators: 300
        max_samples: 64
        contamination: 0.05
        random_state: 42
      KNN:
        n_neighbors: 3
        method: largest
        contamination: 0.05
      OCSVM:
        kernel: rbf
        nu: 0.05
        gamma: 0.1
        contamination: 0.05
      ECOD:
        contamination: 0.05